### ISSUE TITLE
UPDio: generate also output files when no UPD's are found

### ISSUE THREAD

**Issue by ToonRosseel** [nf-cmgg/germline#182]
### Description of feature

Current situation (based on WES run reanalysis): only output file generation when UPD's are detected (~ `*.upd` file is not empty and there is a `*events_plot.png` generated)

Request: also generate output files ( `*.upd` , `*table`, `*event_list`) when no UPD's are detected (~ `*.upd`file is empty and no `*events_plot.png` is generated)

**Comment by nvnieuwk** [comment]
This has already been implemented :)
